version: "3.9"

services:
  server:
    build:
      context: ./server/.
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./server/app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
